//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackJackClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBlackjack")]
    public interface IBlackjack {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjack/GetData", ReplyAction="http://tempuri.org/IBlackjack/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjack/GetData", ReplyAction="http://tempuri.org/IBlackjack/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackjackChannel : BlackJackClient.ServiceReference1.IBlackjack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackjackClient : System.ServiceModel.ClientBase<BlackJackClient.ServiceReference1.IBlackjack>, BlackJackClient.ServiceReference1.IBlackjack {
        
        public BlackjackClient() {
        }
        
        public BlackjackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackjackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ChatCallbacks", ConfigurationName="ServiceReference1.IChat", CallbackContract=typeof(BlackJackClient.ServiceReference1.IChatCallback))]
    public interface IChat {
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddMessage", ReplyAction="ChatCallbacks/IChat/AddMessageResponse")]
        void AddMessage(string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/AddMessage", ReplyAction="ChatCallbacks/IChat/AddMessageResponse")]
        System.Threading.Tasks.Task AddMessageAsync(string playerName, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/Subscribe", ReplyAction="ChatCallbacks/IChat/SubscribeResponse")]
        bool Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/Subscribe", ReplyAction="ChatCallbacks/IChat/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/UnSubscribe", ReplyAction="ChatCallbacks/IChat/UnSubscribeResponse")]
        bool UnSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="ChatCallbacks/IChat/UnSubscribe", ReplyAction="ChatCallbacks/IChat/UnSubscribeResponse")]
        System.Threading.Tasks.Task<bool> UnSubscribeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="ChatCallbacks/IChat/onMessageAdded")]
        void onMessageAdded(System.DateTime dt, string playerName, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatChannel : BlackJackClient.ServiceReference1.IChat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatClient : System.ServiceModel.DuplexClientBase<BlackJackClient.ServiceReference1.IChat>, BlackJackClient.ServiceReference1.IChat {
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddMessage(string playerName, string message) {
            base.Channel.AddMessage(playerName, message);
        }
        
        public System.Threading.Tasks.Task AddMessageAsync(string playerName, string message) {
            return base.Channel.AddMessageAsync(playerName, message);
        }
        
        public bool Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public bool UnSubscribe() {
            return base.Channel.UnSubscribe();
        }
        
        public System.Threading.Tasks.Task<bool> UnSubscribeAsync() {
            return base.Channel.UnSubscribeAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="LoginContract", ConfigurationName="ServiceReference1.ILogin")]
    public interface ILogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/LogIn", ReplyAction="LoginContract/ILogin/LogInResponse")]
        bool LogIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="LoginContract/ILogin/LogIn", ReplyAction="LoginContract/ILogin/LogInResponse")]
        System.Threading.Tasks.Task<bool> LogInAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginChannel : BlackJackClient.ServiceReference1.ILogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<BlackJackClient.ServiceReference1.ILogin>, BlackJackClient.ServiceReference1.ILogin {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogIn(string username, string password) {
            return base.Channel.LogIn(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LogInAsync(string username, string password) {
            return base.Channel.LogInAsync(username, password);
        }
    }
}
